// Shim modules: re-export from window globals so esm.sh's Mantine
// uses the same React/ReactDOM as our UMD scripts.
export default window.React;
export const useState = window.React.useState;
export const useEffect = window.React.useEffect;
export const useRef = window.React.useRef;
export const useMemo = window.React.useMemo;
export const useCallback = window.React.useCallback;
export const useContext = window.React.useContext;
export const useReducer = window.React.useReducer;
export const useLayoutEffect = window.React.useLayoutEffect;
export const useImperativeHandle = window.React.useImperativeHandle;
export const useDebugValue = window.React.useDebugValue;
export const useId = window.React.useId;
export const useSyncExternalStore = window.React.useSyncExternalStore;
export const useTransition = window.React.useTransition;
export const useDeferredValue = window.React.useDeferredValue;
export const useInsertionEffect = window.React.useInsertionEffect;
export const createElement = window.React.createElement;
export const createContext = window.React.createContext;
export const createRef = window.React.createRef;
export const forwardRef = window.React.forwardRef;
export const memo = window.React.memo;
export const Fragment = window.React.Fragment;
export const StrictMode = window.React.StrictMode;
export const Suspense = window.React.Suspense;
export const lazy = window.React.lazy;
export const Children = window.React.Children;
export const cloneElement = window.React.cloneElement;
export const isValidElement = window.React.isValidElement;
export const startTransition = window.React.startTransition;
export const version = window.React.version;
